import type { ExerciseSeed } from "./types";

function drill(exercise: ExerciseSeed): ExerciseSeed {
  return exercise;
}

const golfMonthlyReference =
  "https://www.golfmonthly.com/tips/5-fitness-exercises-that-made-me-a-better-golfer-in-30-days";

const golfMonthlyWorkoutReference =
  "https://www.golfmonthly.com/tips/fitness/best-golf-workouts-10-exercises-for-every-golfer-to-try";

export const expandedExerciseSeeds: ExerciseSeed[] = [
  drill({
    slug: "single-leg-wall-supported-thoracic-rotation",
    name: "Single-Leg Wall-Supported Thoracic Rotation",
    category: "mobility",
    bodyFocus: ["t-spine", "hips", "ankles"],
    swingFocus: ["backswing turn", "posture", "balance"],
    equipment: ["bodyweight", "open_floor", "bench"],
    defaultPrescription: "2 sets x 6 controlled turns per side",
    defaultSets: 2,
    defaultRestSeconds: 25,
    setup: "Stand in golf posture with one foot lightly supported behind you on a wall, bench, or sofa.",
    instructions: ["Soften the standing knee and keep pressure through the whole foot.", "Rotate your rib cage over the standing leg without letting the knee drift.", "Pause at your clean end range, then unwind slowly."],
    feel: "A quiet single-leg base with rotation coming from the upper back.",
    cues: ["Foot tripod", "Turn ribs, not knee", "Stay in posture"],
    commonMistakes: ["Locking the standing knee", "Spinning the pelvis open", "Rushing through the end range"],
    golfBenefit: "Improves torso turn over a stable lower body, which helps separate the backswing without swaying.",
    regression: "Keep both feet on the floor and rotate from golf posture.",
    progression: "Hold a light band across the chest for tension.",
    tags: ["t-spine", "backswing", "balance", "mobility"],
    referenceUrl: golfMonthlyReference,
    referenceTitle: "Golf Monthly: 5 Fitness Exercises That Made Me A Better Golfer"
  }),
  drill({
    slug: "split-stance-rotational-medball-slam",
    name: "Split-Stance Rotational Medball Slam",
    category: "power",
    bodyFocus: ["core", "hips", "lats"],
    swingFocus: ["clubhead speed", "lead-side bracing", "rotation"],
    equipment: ["medball", "open_floor"],
    defaultPrescription: "3 sets x 4 explosive slams per side",
    defaultSets: 3,
    defaultRestSeconds: 75,
    setup: "Take a wide split stance with the lead foot flat and a light medball held at waist height.",
    instructions: ["Load the ball toward the back hip while keeping the front foot rooted.", "Drive the ball up and across your body with speed.", "Slam beside the lead leg and finish balanced before resetting."],
    feel: "Explosive trunk rotation with the lead hip accepting force.",
    cues: ["Load, whip, stick", "Fast arms, quiet base", "Brace the lead side"],
    commonMistakes: ["Using a ball that is too heavy", "Falling out of the split stance", "Throwing with only the arms"],
    golfBenefit: "Trains rotational power and lead-side braking for faster speed without losing posture.",
    regression: "Use a tall-kneeling medball slam.",
    progression: "Add a small step into the slam once landings are controlled.",
    tags: ["medball", "rotational-power", "lead-side", "speed"],
    referenceUrl: golfMonthlyReference,
    referenceTitle: "Golf Monthly: 5 Fitness Exercises That Made Me A Better Golfer"
  }),
  drill({
    slug: "lateral-landing-stick",
    name: "Lateral Landing Stick",
    category: "power",
    bodyFocus: ["glutes", "adductors", "ankles"],
    swingFocus: ["pressure shift", "lead-leg posting", "ground force"],
    equipment: ["bodyweight", "open_floor"],
    defaultPrescription: "3 sets x 4 landings per side",
    defaultSets: 3,
    defaultRestSeconds: 60,
    setup: "Stand on one leg with room to hop sideways and land on the opposite foot.",
    instructions: ["Push laterally from the stance leg.", "Land softly on the opposite foot with knee tracking toes.", "Hold the landing for two seconds before returning."],
    feel: "Athletic side-to-side force with a quiet, controlled landing.",
    cues: ["Push the floor away", "Land quiet", "Own the stick"],
    commonMistakes: ["Letting the knee cave", "Landing tall", "Bouncing out of the landing"],
    golfBenefit: "Builds the ability to shift pressure and stop on the lead side through impact.",
    regression: "Step laterally and hold instead of hopping.",
    progression: "Increase distance while keeping the same quiet landing.",
    tags: ["landing", "ground-force", "lead-leg", "speed"],
    referenceUrl: golfMonthlyReference,
    referenceTitle: "Golf Monthly: 5 Fitness Exercises That Made Me A Better Golfer"
  }),
  drill({
    slug: "side-plank-leg-lift",
    name: "Side Plank Leg Lift",
    category: "control",
    bodyFocus: ["obliques", "glute med", "hips"],
    swingFocus: ["pelvis control", "posture", "lead hip stability"],
    equipment: ["bodyweight", "open_floor"],
    defaultPrescription: "2 sets x 6 lifts per side",
    defaultSets: 2,
    defaultRestSeconds: 45,
    setup: "Set up in a side plank with elbow under shoulder and feet stacked or staggered.",
    instructions: ["Lift the hips into a straight line.", "Raise the top leg without rolling the pelvis open.", "Lower with control and keep breathing."],
    feel: "Side-body tension and outer-hip work without low-back strain.",
    cues: ["Long line", "Hips stacked", "Lift from the hip"],
    commonMistakes: ["Letting hips sag", "Turning toes up", "Holding breath"],
    golfBenefit: "Improves lateral hip and trunk control so the pelvis stays organized during rotation.",
    regression: "Bend the bottom knee for support.",
    progression: "Add a two-second hold at the top of each lift.",
    tags: ["glute-med", "core", "posture", "pelvis"],
    referenceUrl: golfMonthlyReference,
    referenceTitle: "Golf Monthly: 5 Fitness Exercises That Made Me A Better Golfer"
  }),
  drill({
    slug: "reverse-lunge-knee-drive",
    name: "Reverse Lunge Knee Drive",
    category: "strength",
    bodyFocus: ["quads", "glutes", "hip flexors"],
    swingFocus: ["pressure shift", "lead-leg strength", "balance"],
    equipment: ["bodyweight", "dumbbells", "open_floor"],
    defaultPrescription: "3 sets x 6 reps per side",
    defaultSets: 3,
    defaultRestSeconds: 60,
    setup: "Stand tall with ribs stacked over pelvis. Hold light dumbbells only if bodyweight is crisp.",
    instructions: ["Step one leg back into a reverse lunge.", "Drive through the front foot to stand.", "Bring the back knee forward to hip height and pause."],
    feel: "Front-leg strength with a controlled, athletic finish.",
    cues: ["Front heel heavy", "Drive and freeze", "Tall finish"],
    commonMistakes: ["Pushing off the back leg", "Arching the low back", "Crashing into the lunge"],
    golfBenefit: "Builds single-leg strength and balance for a cleaner pressure shift into the lead side.",
    regression: "Tap the back foot down after standing before the knee drive.",
    progression: "Hold dumbbells or add a slow three-second lower.",
    tags: ["single-leg", "lead-leg", "strength", "balance"],
    referenceUrl: golfMonthlyReference,
    referenceTitle: "Golf Monthly: 5 Fitness Exercises That Made Me A Better Golfer"
  }),
  drill({
    slug: "goblet-squat-to-rotation",
    name: "Goblet Squat to Rotation",
    category: "strength",
    bodyFocus: ["quads", "glutes", "t-spine"],
    swingFocus: ["posture", "rotation depth", "lower-body strength"],
    equipment: ["dumbbells", "open_floor"],
    defaultPrescription: "3 sets x 6 reps alternating sides",
    defaultSets: 3,
    defaultRestSeconds: 75,
    setup: "Hold one dumbbell at chest height with feet just outside hip width.",
    instructions: ["Squat with knees tracking toes and chest tall.", "At the bottom, rotate one elbow toward the inside of the same-side knee.", "Return to center and stand with control."],
    feel: "Leg strength paired with a clean upper-back turn.",
    cues: ["Sit between hips", "Elbow turns, heels stay", "Stand tall"],
    commonMistakes: ["Rounding the back", "Letting heels lift", "Twisting through the low back"],
    golfBenefit: "Links squat mobility and thoracic rotation for better address posture and turn quality.",
    regression: "Use bodyweight and a smaller squat depth.",
    progression: "Pause two seconds in the rotated bottom position.",
    tags: ["squat", "t-spine", "posture", "strength"],
    referenceUrl: golfMonthlyWorkoutReference,
    referenceTitle: "Golf Monthly: Best Golf Exercises"
  }),
  drill({
    slug: "dumbbell-rdl-hip-hinge",
    name: "Dumbbell RDL Hip Hinge",
    category: "strength",
    bodyFocus: ["hamstrings", "glutes", "low back"],
    swingFocus: ["golf posture", "posterior chain", "speed base"],
    equipment: ["dumbbells", "open_floor"],
    defaultPrescription: "3 sets x 8 reps",
    defaultSets: 3,
    defaultRestSeconds: 90,
    setup: "Stand with dumbbells in front of the thighs and a soft knee bend.",
    instructions: ["Push hips back as the dumbbells slide down the legs.", "Stop when hamstrings are loaded and spine is still neutral.", "Drive hips forward to stand without leaning back."],
    feel: "Hamstrings and glutes loading like a strong golf setup.",
    cues: ["Hips back", "Long spine", "Crush the floor"],
    commonMistakes: ["Squatting instead of hinging", "Reaching with the neck", "Finishing with a rib flare"],
    golfBenefit: "Builds the hinge and posterior-chain strength needed to hold posture and create speed.",
    regression: "Use a club along the spine to learn the hinge.",
    progression: "Use a slower eccentric or heavier dumbbells.",
    tags: ["hinge", "posterior-chain", "strength", "posture"],
    referenceUrl: golfMonthlyWorkoutReference,
    referenceTitle: "Golf Monthly: Best Golf Exercises"
  }),
  drill({
    slug: "single-arm-dumbbell-row-posture",
    name: "Single-Arm Dumbbell Row in Golf Posture",
    category: "strength",
    bodyFocus: ["lats", "upper back", "core"],
    swingFocus: ["posture", "lat strength", "club control"],
    equipment: ["dumbbells", "bench"],
    defaultPrescription: "3 sets x 8 reps per side",
    defaultSets: 3,
    defaultRestSeconds: 75,
    setup: "Support one hand on a bench and set the torso in a neutral hinge.",
    instructions: ["Let the dumbbell hang under the shoulder.", "Row the elbow toward the back pocket without rotating the chest.", "Lower slowly until the shoulder blade reaches forward."],
    feel: "Lat and mid-back work while the torso stays quiet.",
    cues: ["Elbow to pocket", "Chest square", "Long neck"],
    commonMistakes: ["Shrugging", "Yanking with rotation", "Losing hinge posture"],
    golfBenefit: "Builds upper-back strength for posture endurance and stronger arm-body connection.",
    regression: "Use a lighter dumbbell and pause each rep.",
    progression: "Row from a split stance without bench support.",
    tags: ["row", "lats", "posture", "strength"],
    referenceUrl: golfMonthlyWorkoutReference,
    referenceTitle: "Golf Monthly: Best Golf Exercises"
  }),
  drill({
    slug: "half-kneeling-dumbbell-press",
    name: "Half-Kneeling Dumbbell Press",
    category: "strength",
    bodyFocus: ["shoulders", "core", "hips"],
    swingFocus: ["shoulder mobility", "trunk control", "posture"],
    equipment: ["dumbbells", "open_floor"],
    defaultPrescription: "3 sets x 6 reps per side",
    defaultSets: 3,
    defaultRestSeconds: 75,
    setup: "Half-kneel with the working arm on the same side as the down knee.",
    instructions: ["Squeeze the down-side glute and keep ribs stacked.", "Press the dumbbell overhead without leaning back.", "Lower with control to the shoulder."],
    feel: "Shoulder strength with abs and glute keeping the torso still.",
    cues: ["Glute on", "Ribs down", "Reach tall"],
    commonMistakes: ["Arching the low back", "Letting the elbow flare early", "Losing the half-kneeling base"],
    golfBenefit: "Improves shoulder strength and trunk control without letting the rib cage flare.",
    regression: "Use a lighter load or press from tall kneeling.",
    progression: "Pause overhead for two seconds.",
    tags: ["shoulder", "core", "posture", "strength"],
    referenceUrl: golfMonthlyWorkoutReference,
    referenceTitle: "Golf Monthly: Best Golf Exercises"
  }),
  drill({
    slug: "push-up-shoulder-tap",
    name: "Push-Up Shoulder Tap",
    category: "strength",
    bodyFocus: ["chest", "shoulders", "core"],
    swingFocus: ["upper-body strength", "anti-rotation", "posture"],
    equipment: ["bodyweight", "open_floor"],
    defaultPrescription: "3 sets x 6 reps plus 6 taps",
    defaultSets: 3,
    defaultRestSeconds: 75,
    setup: "Set up in a strong plank with hands under shoulders and feet slightly wider than hips.",
    instructions: ["Perform one controlled push-up.", "At the top, tap opposite shoulder without shifting hips.", "Alternate taps and reset your plank before the next rep."],
    feel: "Upper-body effort with the trunk resisting sway.",
    cues: ["Push the floor", "Quiet hips", "Brace before tap"],
    commonMistakes: ["Sagging hips", "Rushing the taps", "Flaring elbows too wide"],
    golfBenefit: "Builds push strength and anti-rotation control that supports speed work.",
    regression: "Do incline push-ups on a bench.",
    progression: "Slow the lowering phase to three seconds.",
    tags: ["push", "anti-rotation", "upper-body", "strength"]
  }),
  drill({
    slug: "dead-bug-band-pulldown",
    name: "Dead Bug Band Pulldown",
    category: "control",
    bodyFocus: ["abs", "lats", "hip flexors"],
    swingFocus: ["rib control", "posture", "sequencing"],
    equipment: ["bands", "open_floor"],
    defaultPrescription: "2 sets x 6 reps per side",
    defaultSets: 2,
    defaultRestSeconds: 45,
    setup: "Lie on your back holding a band anchored overhead with knees at tabletop.",
    instructions: ["Pull the band until arms are over the chest.", "Exhale and lower one heel toward the floor.", "Return slowly without letting the low back arch."],
    feel: "Abs locking the ribs down while lats stay engaged.",
    cues: ["Exhale first", "Back heavy", "Slow heel"],
    commonMistakes: ["Arching the low back", "Pulling the band with bent wrists", "Moving too fast"],
    golfBenefit: "Teaches rib and pelvis control that keeps rotation from leaking into extension.",
    regression: "Keep both feet on the floor and march one leg at a time.",
    progression: "Lower the opposite arm and leg together.",
    tags: ["core", "lats", "rib-control", "posture"]
  }),
  drill({
    slug: "bear-crawl-shoulder-tap",
    name: "Bear Crawl Shoulder Tap",
    category: "control",
    bodyFocus: ["abs", "shoulders", "hips"],
    swingFocus: ["anti-rotation", "posture", "pelvis control"],
    equipment: ["bodyweight", "open_floor"],
    defaultPrescription: "2 sets x 8 taps per side",
    defaultSets: 2,
    defaultRestSeconds: 45,
    setup: "Start on hands and knees, then hover knees one inch off the floor with toes tucked.",
    instructions: ["Brace as if balancing a glass on your low back.", "Tap one hand to the opposite shoulder without shifting hips.", "Replace the hand quietly and alternate sides."],
    feel: "Deep core and shoulder stability while the pelvis stays level.",
    cues: ["Knees hover", "Quiet hips", "Tap slow"],
    commonMistakes: ["Rocking side to side", "Letting knees drift high", "Holding breath"],
    golfBenefit: "Builds anti-rotation control so the trunk can transfer force without wobbling.",
    regression: "Keep knees on the floor and perform slow shoulder taps.",
    progression: "Move feet closer together while keeping hips still.",
    tags: ["anti-rotation", "core", "shoulders", "control"]
  }),
  drill({
    slug: "plank-dumbbell-pull-through",
    name: "Plank Dumbbell Pull-Through",
    category: "control",
    bodyFocus: ["abs", "shoulders", "lats"],
    swingFocus: ["anti-rotation", "posture", "core stability"],
    equipment: ["dumbbells", "open_floor"],
    defaultPrescription: "3 sets x 6 pulls per side",
    defaultSets: 3,
    defaultRestSeconds: 60,
    setup: "Start in a plank with a dumbbell outside one hand and feet wider than hips.",
    instructions: ["Reach the opposite hand under your chest.", "Drag the dumbbell across without twisting the pelvis.", "Reset your hand under the shoulder before switching sides."],
    feel: "A strong brace that resists rotation while the arm moves.",
    cues: ["Wide feet", "Hips quiet", "Drag slow"],
    commonMistakes: ["Rocking side to side", "Letting shoulders shrug", "Holding breath"],
    golfBenefit: "Builds trunk stiffness that lets rotation happen powerfully instead of leaking through the spine.",
    regression: "Use no load and tap the floor side to side.",
    progression: "Use a heavier dumbbell or narrower foot stance.",
    tags: ["anti-rotation", "core", "plank", "control"]
  }),
  drill({
    slug: "medball-shot-put-throw",
    name: "Medball Shot Put Throw",
    category: "power",
    bodyFocus: ["chest", "core", "hips"],
    swingFocus: ["upper-body power", "sequencing", "clubhead speed"],
    equipment: ["medball", "open_floor"],
    defaultPrescription: "3 sets x 4 throws per side",
    defaultSets: 3,
    defaultRestSeconds: 90,
    setup: "Stand side-on to a wall with a light medball near the trail shoulder.",
    instructions: ["Load into the trail hip with the ball by the shoulder.", "Drive from the ground and punch the ball into the wall.", "Catch, reset fully, and keep each throw explosive."],
    feel: "Ground-up speed finishing through the chest and arm.",
    cues: ["Load hip", "Punch fast", "Reset every rep"],
    commonMistakes: ["Using too heavy a ball", "Arm-only throws", "Letting reps blur together"],
    golfBenefit: "Develops upper-body and trunk power that transfers to faster downswing intent.",
    regression: "Throw from a half-kneeling stance.",
    progression: "Add a small step into the throw.",
    tags: ["medball", "power", "speed", "upper-body"]
  }),
  drill({
    slug: "seated-medball-chest-pass",
    name: "Seated Medball Chest Pass",
    category: "power",
    bodyFocus: ["chest", "triceps", "core"],
    swingFocus: ["upper-body speed", "power", "arm acceleration"],
    equipment: ["medball", "open_floor"],
    defaultPrescription: "3 sets x 5 explosive passes",
    defaultSets: 3,
    defaultRestSeconds: 75,
    setup: "Sit tall facing a wall with legs extended or lightly bent and a light medball at the chest.",
    instructions: ["Brace tall without leaning back.", "Throw the ball into the wall as fast as possible.", "Catch, reset the chest position, and repeat."],
    feel: "Fast upper-body acceleration without lumbar extension.",
    cues: ["Tall spine", "Fast hands", "Reset posture"],
    commonMistakes: ["Leaning back before the throw", "Choosing a heavy ball", "Letting shoulders roll forward"],
    golfBenefit: "Builds upper-body explosiveness without letting the lower body dominate the rep.",
    regression: "Use a lighter ball or stand closer to the wall.",
    progression: "Add a pause before each throw.",
    tags: ["medball", "upper-body-power", "speed", "chest-pass"]
  }),
  drill({
    slug: "standing-long-jump-stick",
    name: "Standing Long Jump Stick",
    category: "power",
    bodyFocus: ["glutes", "quads", "ankles"],
    swingFocus: ["lower-body power", "ground force", "speed"],
    equipment: ["bodyweight", "open_floor"],
    defaultPrescription: "4 sets x 3 jumps",
    defaultSets: 4,
    defaultRestSeconds: 75,
    setup: "Stand with feet hip-width and room to jump forward.",
    instructions: ["Load the hips back with arms behind you.", "Jump forward explosively and land with both feet.", "Stick the landing for two seconds before stepping back."],
    feel: "Fast lower-body force with a controlled finish.",
    cues: ["Load hips", "Explode forward", "Stick quiet"],
    commonMistakes: ["Landing stiff", "Knees collapsing", "Doing too many reps fatigued"],
    golfBenefit: "Trains lower-body power and braking, two key ingredients for speed development.",
    regression: "Perform broad jump to a smaller distance.",
    progression: "Measure distance and track best clean jump.",
    tags: ["jump", "lower-body-power", "ground-force", "speed"]
  }),
  drill({
    slug: "box-jump-step-down",
    name: "Box Jump with Step-Down",
    category: "power",
    bodyFocus: ["quads", "glutes", "calves"],
    swingFocus: ["explosive strength", "speed", "athleticism"],
    equipment: ["bench", "bodyweight"],
    defaultPrescription: "4 sets x 3 jumps",
    defaultSets: 4,
    defaultRestSeconds: 90,
    setup: "Stand in front of a low, stable box or bench with enough height to jump safely.",
    instructions: ["Load into a quarter squat.", "Jump onto the box and land quietly.", "Stand tall, then step down instead of jumping down."],
    feel: "Explosive takeoff with soft, controlled landing.",
    cues: ["Low box, high intent", "Land soft", "Step down"],
    commonMistakes: ["Picking a box too high", "Crashing into the landing", "Jumping down between reps"],
    golfBenefit: "Develops lower-body explosiveness that supports clubhead speed training.",
    regression: "Use snap-downs or squat jumps without a box.",
    progression: "Slightly increase height while preserving quiet landings.",
    tags: ["jump", "power", "speed", "lower-body"]
  }),
  drill({
    slug: "skater-hop-stick",
    name: "Skater Hop Stick",
    category: "power",
    bodyFocus: ["glutes", "adductors", "ankles"],
    swingFocus: ["lateral power", "pressure shift", "lead-leg posting"],
    equipment: ["bodyweight", "open_floor"],
    defaultPrescription: "3 sets x 4 hops per side",
    defaultSets: 3,
    defaultRestSeconds: 75,
    setup: "Stand on one leg with the opposite foot hovering behind you.",
    instructions: ["Hop laterally to the opposite foot.", "Stick the landing with the hip back and knee tracking toes.", "Pause before hopping back."],
    feel: "Side-to-side athletic power with balance at each finish.",
    cues: ["Push sideways", "Hip back", "Freeze"],
    commonMistakes: ["Turning it into cardio", "Letting the knee dive in", "Landing on the toes"],
    golfBenefit: "Builds lateral force and lead-side braking for a stronger shift into impact.",
    regression: "Do lateral step-and-stick reps.",
    progression: "Increase hop distance or hold light dumbbells.",
    tags: ["lateral", "power", "lead-side", "ground-force"]
  }),
  drill({
    slug: "split-squat-iso-hold",
    name: "Split Squat Iso Hold",
    category: "strength",
    bodyFocus: ["quads", "glutes", "feet"],
    swingFocus: ["lead-leg strength", "posture", "pressure shift"],
    equipment: ["bodyweight", "dumbbells", "open_floor"],
    defaultPrescription: "3 sets x 20-second hold per side",
    defaultSets: 3,
    defaultRestSeconds: 60,
    setup: "Set up in a split stance with both knees softly bent and torso tall.",
    instructions: ["Lower until the front leg is working hard but controlled.", "Hold with front foot rooted and knee tracking toes.", "Stand, rest, and switch sides."],
    feel: "A steady burn in the front leg with a strong foot tripod.",
    cues: ["Front heel heavy", "Knee tracks", "Tall ribs"],
    commonMistakes: ["Letting the front knee collapse", "Leaning way forward", "Holding breath"],
    golfBenefit: "Builds lead-leg capacity to post and rotate without standing up.",
    regression: "Hold a higher position.",
    progression: "Hold dumbbells or increase to 30 seconds.",
    tags: ["isometric", "single-leg", "lead-leg", "strength"]
  }),
  drill({
    slug: "lateral-lunge-to-post",
    name: "Lateral Lunge to Post",
    category: "strength",
    bodyFocus: ["adductors", "glutes", "hips"],
    swingFocus: ["trail-hip load", "lead-side post", "rotation"],
    equipment: ["bodyweight", "dumbbells", "open_floor"],
    defaultPrescription: "3 sets x 6 reps per side",
    defaultSets: 3,
    defaultRestSeconds: 75,
    setup: "Stand tall with feet together and room to step sideways.",
    instructions: ["Step into a lateral lunge with hips back.", "Drive through the lunging foot to return.", "Finish tall on the stance leg like a lead-side post."],
    feel: "Hip loading on the way out and strong posting on the way back.",
    cues: ["Sit into hip", "Push floor", "Post tall"],
    commonMistakes: ["Letting the stepping knee cave", "Turning the toes too far out", "Pushing off the straight leg"],
    golfBenefit: "Trains frontal-plane hip strength that supports loading and posting in the swing.",
    regression: "Use a smaller step and no load.",
    progression: "Hold one dumbbell goblet-style.",
    tags: ["lateral", "hip-load", "lead-post", "strength"]
  }),
  drill({
    slug: "copenhagen-side-plank-short-lever",
    name: "Short-Lever Copenhagen Side Plank",
    category: "control",
    bodyFocus: ["adductors", "obliques", "hips"],
    swingFocus: ["pelvis control", "lead hip", "posture"],
    equipment: ["bench", "bodyweight"],
    defaultPrescription: "2 sets x 15-second hold per side",
    defaultSets: 2,
    defaultRestSeconds: 45,
    setup: "Place the top knee on a bench and support yourself on the bottom elbow.",
    instructions: ["Lift hips until the body forms a straight line.", "Gently pull the top knee down into the bench.", "Hold while breathing slowly."],
    feel: "Inner thigh and side abs working together.",
    cues: ["Stack ribs", "Pull bench down", "Breathe"],
    commonMistakes: ["Using the long-lever version too soon", "Sagging at the hips", "Shrugging the shoulder"],
    golfBenefit: "Strengthens adductors and lateral core for better pelvis control during rotation.",
    regression: "Use a side plank without the bench.",
    progression: "Move to a long-lever Copenhagen hold.",
    tags: ["adductors", "core", "pelvis", "control"]
  }),
  drill({
    slug: "banded-hip-airplane",
    name: "Banded Hip Airplane",
    category: "control",
    bodyFocus: ["hips", "glutes", "feet"],
    swingFocus: ["hip rotation", "balance", "early extension"],
    equipment: ["bands", "open_floor"],
    defaultPrescription: "2 sets x 4 slow reps per side",
    defaultSets: 2,
    defaultRestSeconds: 45,
    setup: "Stand on one leg in a small hinge with a band giving light support or feedback.",
    instructions: ["Open the pelvis slowly while the stance knee tracks toes.", "Rotate closed without losing foot pressure.", "Keep the torso long and the hip deep."],
    feel: "Deep stance-hip control and foot stability.",
    cues: ["Hip socket turns", "Foot stays alive", "Move slow"],
    commonMistakes: ["Spinning through the low back", "Locking the stance knee", "Letting the arch collapse"],
    golfBenefit: "Builds active hip rotation control for a deeper pivot and less early extension.",
    regression: "Hold a wall or club for balance.",
    progression: "Remove hand support and pause at each end range.",
    tags: ["hip-rotation", "balance", "early-extension", "control"]
  }),
  drill({
    slug: "quadruped-t-spine-thread-the-needle",
    name: "Quadruped T-Spine Thread the Needle",
    category: "mobility",
    bodyFocus: ["t-spine", "shoulders", "lats"],
    swingFocus: ["rotation", "backswing turn", "posture"],
    equipment: ["bodyweight", "open_floor"],
    defaultPrescription: "2 sets x 6 reps per side",
    defaultSets: 2,
    defaultRestSeconds: 20,
    setup: "Start on hands and knees with hips over knees and one hand behind the head.",
    instructions: ["Thread the elbow toward the opposite wrist.", "Rotate open toward the ceiling without shifting hips.", "Pause and exhale at the top."],
    feel: "Upper-back rotation without low-back twisting.",
    cues: ["Hips still", "Elbow leads", "Exhale open"],
    commonMistakes: ["Rocking hips side to side", "Forcing neck rotation", "Moving too quickly"],
    golfBenefit: "Restores thoracic rotation so the hips and low back do not have to compensate.",
    regression: "Place the hand on the ribs instead of behind the head.",
    progression: "Add a reach to the ceiling at end range.",
    tags: ["t-spine", "mobility", "rotation", "daily"]
  }),
  drill({
    slug: "standing-band-chop",
    name: "Standing Band Chop",
    category: "control",
    bodyFocus: ["core", "obliques", "hips"],
    swingFocus: ["sequencing", "anti-extension", "rotation control"],
    equipment: ["bands", "open_floor"],
    defaultPrescription: "3 sets x 8 reps per side",
    defaultSets: 3,
    defaultRestSeconds: 45,
    setup: "Anchor a band high and stand in an athletic stance side-on to the anchor.",
    instructions: ["Pull the band down and across the body.", "Let the ribs turn slightly while pelvis stays controlled.", "Return slowly without losing posture."],
    feel: "Abs guiding rotation while the feet stay grounded.",
    cues: ["Ribs over hips", "Pull across", "Slow return"],
    commonMistakes: ["Yanking with arms", "Over-rotating the pelvis", "Arching at the finish"],
    golfBenefit: "Builds trunk control for cleaner sequencing from backswing into downswing.",
    regression: "Use a lighter band and smaller range.",
    progression: "Perform from a split stance.",
    tags: ["band", "core", "rotation-control", "sequencing"]
  }),
  drill({
    slug: "standing-band-lift",
    name: "Standing Band Lift",
    category: "control",
    bodyFocus: ["core", "shoulders", "hips"],
    swingFocus: ["backswing control", "rib control", "posture"],
    equipment: ["bands", "open_floor"],
    defaultPrescription: "3 sets x 8 reps per side",
    defaultSets: 3,
    defaultRestSeconds: 45,
    setup: "Anchor a band low and stand side-on in a stable athletic stance.",
    instructions: ["Pull the band upward across the body.", "Keep ribs stacked and finish tall.", "Return slowly to the low anchor position."],
    feel: "Controlled diagonal tension through abs and shoulders.",
    cues: ["Zip up abs", "Lift with control", "No lean back"],
    commonMistakes: ["Leaning away from the anchor", "Shrugging", "Letting the knees collapse"],
    golfBenefit: "Improves diagonal trunk control for better backswing organization.",
    regression: "Use a lighter band or kneeling stance.",
    progression: "Add a half-kneeling version with a pause at the top.",
    tags: ["band", "core", "backswing", "control"]
  }),
  drill({
    slug: "banded-lat-stretch-rotation",
    name: "Banded Lat Stretch with Rotation",
    category: "mobility",
    bodyFocus: ["lats", "t-spine", "shoulders"],
    swingFocus: ["backswing width", "shoulder mobility", "rotation"],
    equipment: ["bands", "open_floor"],
    defaultPrescription: "2 sets x 5 breaths per side",
    defaultSets: 2,
    defaultRestSeconds: 20,
    setup: "Anchor a band overhead, grab it with one hand, and hinge hips back until the lat is gently tensioned.",
    instructions: ["Sink hips back and keep ribs down.", "Take a slow breath into the stretched side.", "Rotate the chest slightly open and return."],
    feel: "A long stretch from shoulder through side ribs without pinching.",
    cues: ["Ribs down", "Breathe wide", "Rotate gently"],
    commonMistakes: ["Arching the low back", "Pulling into shoulder pain", "Holding breath"],
    golfBenefit: "Frees the lats and rib cage for a wider, easier backswing turn.",
    regression: "Use no band and perform child's pose reaches.",
    progression: "Add a longer exhale at end range.",
    tags: ["lat", "mobility", "backswing", "t-spine"]
  }),
  drill({
    slug: "glute-bridge-march",
    name: "Glute Bridge March",
    category: "control",
    bodyFocus: ["glutes", "hamstrings", "core"],
    swingFocus: ["pelvis control", "posterior chain", "posture"],
    equipment: ["bodyweight", "open_floor"],
    defaultPrescription: "2 sets x 8 marches per side",
    defaultSets: 2,
    defaultRestSeconds: 45,
    setup: "Lie on your back with knees bent, heels down, and hips lifted into a bridge.",
    instructions: ["Keep ribs down and glutes lightly squeezed.", "Lift one knee without letting the pelvis twist.", "Replace the foot quietly and alternate."],
    feel: "Glutes holding the pelvis level while legs move.",
    cues: ["Hips level", "Heel heavy", "Quiet march"],
    commonMistakes: ["Overarching the back", "Letting hips drop", "Pushing through toes"],
    golfBenefit: "Builds glute and pelvis control for a stable base during rotation.",
    regression: "Hold a normal glute bridge.",
    progression: "Add a mini-band around the knees.",
    tags: ["glutes", "pelvis", "posterior-chain", "control"]
  }),
  drill({
    slug: "hamstring-walkout",
    name: "Hamstring Walkout",
    category: "strength",
    bodyFocus: ["hamstrings", "glutes", "core"],
    swingFocus: ["posterior chain", "posture", "injury resilience"],
    equipment: ["bodyweight", "open_floor"],
    defaultPrescription: "3 sets x 5 walkouts",
    defaultSets: 3,
    defaultRestSeconds: 60,
    setup: "Start in a glute bridge with heels close to the hips and toes lifted.",
    instructions: ["Walk heels away one small step at a time.", "Keep hips lifted and ribs down.", "Walk heels back under knees before lowering."],
    feel: "Hamstrings working hard while the pelvis stays level.",
    cues: ["Small steps", "Hips high", "Ribs quiet"],
    commonMistakes: ["Taking huge steps", "Letting hips sag", "Cramping from pushing too hard"],
    golfBenefit: "Strengthens hamstrings and glutes that support hinge posture and speed training.",
    regression: "Do bridge holds for time.",
    progression: "Slow each walkout step to three seconds.",
    tags: ["hamstrings", "posterior-chain", "strength", "posture"]
  }),
  drill({
    slug: "wall-sit-heel-raise",
    name: "Wall Sit Heel Raise",
    category: "strength",
    bodyFocus: ["quads", "calves", "ankles"],
    swingFocus: ["posture endurance", "ankle control", "lower-body strength"],
    equipment: ["bodyweight", "open_floor"],
    defaultPrescription: "2 sets x 20-second wall sit plus 8 heel raises",
    defaultSets: 2,
    defaultRestSeconds: 45,
    setup: "Sit against a wall with knees bent and feet under knees.",
    instructions: ["Hold the wall sit with ribs stacked.", "Raise both heels while keeping knees tracking toes.", "Lower heels slowly and keep the wall-sit height."],
    feel: "Quads and calves working while posture stays steady.",
    cues: ["Back flat", "Knees forward", "Slow heels"],
    commonMistakes: ["Sliding too low", "Letting knees cave", "Bouncing heel raises"],
    golfBenefit: "Builds knee and ankle tolerance for staying in posture through rotation.",
    regression: "Hold the wall sit without heel raises.",
    progression: "Hold a light dumbbell goblet-style.",
    tags: ["ankle", "quads", "posture", "strength"]
  }),
  drill({
    slug: "club-speed-step-swing",
    name: "Club Speed Step Swing",
    category: "power",
    bodyFocus: ["hips", "core", "shoulders"],
    swingFocus: ["swing speed", "sequencing", "pressure shift"],
    equipment: ["golf_club", "open_floor"],
    defaultPrescription: "3 sets x 5 fast rehearsal swings each direction",
    defaultSets: 3,
    defaultRestSeconds: 60,
    setup: "Hold a golf club or alignment stick with enough room for fast rehearsal swings.",
    instructions: ["Start with feet together and the club set like an address position.", "Step toward the target as you start the downswing rehearsal.", "Swing fast, finish balanced, and reset fully."],
    feel: "A synced pressure shift that lets the club move faster without strain.",
    cues: ["Step, then rip", "Finish tall", "Reset every rep"],
    commonMistakes: ["Swinging before the step", "Losing balance", "Doing reps while tired"],
    golfBenefit: "Connects athletic stepping, sequencing, and speed intent in a golf-specific pattern.",
    regression: "Make slow step swings at half speed.",
    progression: "Track radar speed if available and stop when speed drops.",
    tags: ["speed", "golf-club", "sequencing", "pressure-shift"]
  })
];
