import type { BaselineResultInput, BaselineTestSeed, ExerciseSeed } from "./types";

export const baselineTests: BaselineTestSeed[] = [
  { slug: "hip-ir-left", name: "Hip Internal Rotation - Left", category: "mobility", side: "left", unit: "degrees", priority: 1 },
  { slug: "hip-ir-right", name: "Hip Internal Rotation - Right", category: "mobility", side: "right", unit: "degrees", priority: 1 },
  { slug: "hip-er-left", name: "Hip External Rotation - Left", category: "mobility", side: "left", unit: "degrees", priority: 3 },
  { slug: "hip-er-right", name: "Hip External Rotation - Right", category: "mobility", side: "right", unit: "degrees", priority: 3 },
  { slug: "t-spine-rotation-left", name: "T-Spine Rotation - Left", category: "mobility", side: "left", unit: "degrees", priority: 1 },
  { slug: "t-spine-rotation-right", name: "T-Spine Rotation - Right", category: "mobility", side: "right", unit: "degrees", priority: 1 },
  { slug: "ankle-dorsiflexion-left", name: "Ankle Dorsiflexion - Left", category: "mobility", side: "left", unit: "inches", priority: 2 },
  { slug: "ankle-dorsiflexion-right", name: "Ankle Dorsiflexion - Right", category: "mobility", side: "right", unit: "inches", priority: 2 },
  { slug: "single-leg-squat-left", name: "Single-Leg Squat Quality - Left", category: "control", side: "left", unit: "rating", priority: 2 },
  { slug: "single-leg-squat-right", name: "Single-Leg Squat Quality - Right", category: "control", side: "right", unit: "rating", priority: 2 },
  { slug: "pelvic-rotation-control", name: "Pelvic Rotation Control", category: "control", side: "center", unit: "rating", priority: 1 },
  { slug: "pelvic-tilt-control", name: "Pelvic Tilt Control", category: "control", side: "center", unit: "rating", priority: 2 },
  { slug: "rotational-medball-throw-left", name: "Rotational Medball Throw - Left", category: "power", side: "left", unit: "feet", priority: 2 },
  { slug: "rotational-medball-throw-right", name: "Rotational Medball Throw - Right", category: "power", side: "right", unit: "feet", priority: 2 },
  { slug: "driver-swing-speed", name: "Driver Swing Speed", category: "speed", side: "optional", unit: "mph", priority: 5 }
];

function drill(exercise: ExerciseSeed): ExerciseSeed {
  return exercise;
}

export const exercises: ExerciseSeed[] = [
  drill({
    slug: "90-90-lead-hip-ir-lift-off",
    name: "90/90 Lead Hip IR Lift-Off",
    category: "control",
    bodyFocus: ["lead hip", "deep rotators", "pelvis"],
    swingFocus: ["lead hip internal rotation", "posture", "early extension"],
    equipment: ["bodyweight", "open_floor"],
    defaultPrescription: "2 sets x 5 reps with 3-second holds per side",
    defaultSets: 2,
    defaultRestSeconds: 30,
    setup: "Sit in a 90/90 position with the front shin across your body and the back leg bent behind you. Tall spine, hands light on the floor only if needed.",
    instructions: ["Find a tall rib-over-pelvis position before moving.", "Without leaning away, try to float the back ankle one inch off the floor.", "Pause for three seconds, lower quietly, and reset your posture."],
    feel: "A small, deep effort in the outside/back hip. It should feel precise, not like low-back tension.",
    cues: ["Stay tall", "Move the femur in the socket", "Keep the pelvis quiet"],
    commonMistakes: ["Leaning the trunk to fake range", "Pushing hard through the hands", "Cramping because the lift is too high"],
    golfBenefit: "Builds active lead hip internal rotation so the pelvis can keep turning instead of thrusting toward the ball.",
    regression: "Use both hands behind you and make the lift-off smaller.",
    progression: "Add a two-second hover and slow lower on each rep.",
    tags: ["lead-hip-ir", "early-extension", "mobility-control", "daily"]
  }),
  drill({
    slug: "medball-hip-er-to-ir",
    name: "Medball External to Internal Hip Rotation",
    category: "control",
    bodyFocus: ["hips", "core"],
    swingFocus: ["lead hip rotation", "posture", "shallowing"],
    equipment: ["medball", "open_floor"],
    defaultPrescription: "2 sets x 6 slow reps per side",
    defaultSets: 2,
    defaultRestSeconds: 45,
    setup: "Stand in golf posture holding a light medball. Load into the hip externally, then rotate into controlled internal rotation without standing up.",
    instructions: ["Set your ribs down and hinge into golf posture.", "Rotate into the hip as if the femur is turning under a quiet pelvis.", "Finish with the lead hip deep and chest still covering the ball line."],
    feel: "Controlled pressure into the outside hip and glute, with your torso organized over your pelvis.",
    cues: ["Move from the hip, not the low back", "Keep pelvis depth", "Finish balanced"],
    commonMistakes: ["Rushing the turn", "Standing up out of posture", "Letting the knee collapse"],
    golfBenefit: "Builds active lead hip internal rotation for a deeper, cleaner downswing pivot.",
    regression: "Perform without load.",
    progression: "Add a pause at end-range internal rotation.",
    tags: ["lead-hip-ir", "shallowing", "posture", "medball"]
  }),
  drill({
    slug: "half-kneeling-t-spine-open-book",
    name: "Half-Kneeling T-Spine Open Book",
    category: "mobility",
    bodyFocus: ["t-spine", "ribs", "hips"],
    swingFocus: ["turn depth", "separation", "low back safety"],
    equipment: ["bodyweight", "open_floor"],
    defaultPrescription: "2 sets x 6 breaths per side",
    defaultSets: 2,
    defaultRestSeconds: 20,
    setup: "Half-kneel with front knee up, back knee down, hips square, and hands together in front of chest.",
    instructions: ["Exhale to stack ribs over pelvis.", "Rotate your chest open while keeping the belt buckle quiet.", "Pause, breathe into the open ribs, then return slowly."],
    feel: "Upper-back opening and rib expansion without pinching in the low back.",
    cues: ["Rotate ribs, not lumbar spine", "Keep front foot heavy", "Exhale into range"],
    commonMistakes: ["Arching to fake rotation", "Letting the front knee drift", "Moving fast through the sticky point"],
    golfBenefit: "Improves torso rotation so you do not have to steal motion from the lumbar spine or early extend for space.",
    regression: "Do it side-lying with knees stacked.",
    progression: "Hold a light medball and add a controlled reach.",
    tags: ["t-spine", "separation", "mobility", "daily"]
  }),
  drill({
    slug: "weighted-kot-lunge",
    name: "Weighted Knee-Over-Toe Lunge",
    category: "strength",
    bodyFocus: ["ankles", "quads", "feet"],
    swingFocus: ["posture", "pressure shift", "lead-leg post"],
    equipment: ["dumbbells", "bodyweight", "open_floor"],
    defaultPrescription: "2-3 sets x 6 reps per side",
    defaultSets: 3,
    defaultRestSeconds: 75,
    setup: "Take a short split stance. Hold light dumbbells if available. Let the front knee travel forward while the heel stays heavy.",
    instructions: ["Keep the front heel down as the knee tracks over the middle toes.", "Lower until the ankle or knee reaches a comfortable end range.", "Push the floor away and stand tall without bouncing."],
    feel: "A strong stretch/load through the ankle and quad, with the foot staying rooted.",
    cues: ["Heel heavy", "Knee follows toes", "Slow down the bottom"],
    commonMistakes: ["Heel popping up", "Knee diving inside", "Loading too heavy too soon"],
    golfBenefit: "Improves ankle dorsiflexion and leg strength so you can rotate while staying in posture.",
    regression: "Use bodyweight and hold a wall for balance.",
    progression: "Hold dumbbells or add a three-second eccentric.",
    tags: ["ankle-dorsiflexion", "lead-leg-post", "posture", "strength"]
  }),
  drill({
    slug: "single-leg-squat-to-box",
    name: "Single-Leg Squat to Box",
    category: "strength",
    bodyFocus: ["glutes", "quads", "feet"],
    swingFocus: ["posting", "low point", "pelvic control"],
    equipment: ["bench", "bodyweight"],
    defaultPrescription: "3 sets x 5 reps per side",
    defaultSets: 3,
    defaultRestSeconds: 90,
    setup: "Stand on one leg in front of a box or bench. Reach the free leg forward slightly and keep the stance foot tripod heavy.",
    instructions: ["Sit back and down toward the box without collapsing the arch.", "Tap the box lightly, then drive through the full foot to stand.", "Reset balance before the next rep."],
    feel: "Glute and quad working together while the pelvis stays level.",
    cues: ["Tripod foot", "Knee tracks over laces", "Own the tap"],
    commonMistakes: ["Dropping onto the box", "Knee cave", "Pelvis hiking or rotating"],
    golfBenefit: "Builds lead-leg strength and control for a stable post through impact.",
    regression: "Use a higher box or light hand support.",
    progression: "Lower the box or hold a dumbbell goblet-style.",
    tags: ["single-leg", "lead-leg-post", "low-point", "strength"]
  }),
  drill({
    slug: "pelvic-rotation-sticks",
    name: "Pelvic Rotation with Club Across Chest",
    category: "control",
    bodyFocus: ["pelvis", "core", "hips"],
    swingFocus: ["pelvic control", "separation", "early extension"],
    equipment: ["golf_club", "open_floor"],
    defaultPrescription: "2 sets x 8 controlled reps each direction",
    defaultSets: 2,
    defaultRestSeconds: 30,
    setup: "Stand in golf posture with a club across your chest. Keep your chest quiet while the pelvis rotates under you.",
    instructions: ["Set posture with soft knees and ribs down.", "Rotate the belt buckle right and left without changing spine angle.", "Pause where you usually lose posture and breathe."],
    feel: "Obliques and hip rotators controlling the pelvis without your head bobbing up.",
    cues: ["Chest quiet", "Belt buckle turns", "Keep depth"],
    commonMistakes: ["Swaying side to side", "Standing up", "Turning shoulders instead of pelvis"],
    golfBenefit: "Trains the exact pelvic control needed to rotate instead of thrusting toward the ball.",
    regression: "Do it standing tall with hands on hips.",
    progression: "Add a mini-band above the knees.",
    tags: ["pelvic-control", "early-extension", "shallowing", "golf-club"]
  }),
  drill({
    slug: "medball-scoop-toss",
    name: "Rotational Medball Scoop Toss",
    category: "power",
    bodyFocus: ["hips", "core", "upper body"],
    swingFocus: ["swing speed", "sequence", "ground force"],
    equipment: ["medball", "open_floor"],
    defaultPrescription: "4 sets x 4 throws per side",
    defaultSets: 4,
    defaultRestSeconds: 75,
    setup: "Stand side-on to a wall with a light medball. Start athletic, load into the trail hip, and throw like a low-to-high rotational scoop.",
    instructions: ["Load the inside of the trail foot and hip.", "Push the ground, rotate the pelvis, then let the chest and arms whip the ball.", "Reset fully between throws."],
    feel: "Fast hip-to-torso sequencing, not an arm-only throw.",
    cues: ["Load, fire, finish", "Throw fast, not heavy", "Reset each rep"],
    commonMistakes: ["Using a ball that is too heavy", "Spinning without pressure shift", "Catching and rushing reps"],
    golfBenefit: "Develops rotational power and sequencing for clubhead speed.",
    regression: "Half-kneeling scoop toss.",
    progression: "Step-behind scoop toss.",
    tags: ["speed", "rotational-power", "medball", "sequence"]
  }),
  drill({
    slug: "band-assisted-shallow-pump",
    name: "Band-Assisted Shallow Pump",
    category: "control",
    bodyFocus: ["shoulders", "lats", "core"],
    swingFocus: ["shallowing", "trail elbow", "transition"],
    equipment: ["bands", "golf_club"],
    defaultPrescription: "2 sets x 6 slow pumps",
    defaultSets: 2,
    defaultRestSeconds: 45,
    setup: "Anchor a light band above trail-side shoulder height and hold a club or handle in golf posture. The band should gently pull you steep so you can resist into a shallower slot.",
    instructions: ["Make a slow backswing to lead arm parallel.", "Let the lower body start while the hands fall slightly behind you.", "Pump into the delivery position without throwing the shoulders open."],
    feel: "Trail elbow softening down in front of the rib cage while the chest stays patient.",
    cues: ["Lower body first", "Hands fall, chest waits", "No yank"],
    commonMistakes: ["Pulling with the arms", "Standing up", "Over-rotating the shoulders early"],
    golfBenefit: "Connects mobility/control work to the feel of shallowing in transition.",
    regression: "Do slow motion without the band.",
    progression: "Add a half-speed rehearsal swing after each pump.",
    tags: ["shallowing", "transition", "bands", "golf-specific"]
  }),
  drill({
    slug: "club-across-hips-depth-turn",
    name: "Club-Across-Hips Depth Turn",
    category: "control",
    bodyFocus: ["hips", "pelvis", "feet"],
    swingFocus: ["pelvic depth", "early extension", "rotation"],
    equipment: ["golf_club", "open_floor"],
    defaultPrescription: "2 sets x 8 slow turns",
    defaultSets: 2,
    defaultRestSeconds: 30,
    setup: "Place a club across the front of your hips in golf posture. Stand near a wall or chair lightly touching your glutes.",
    instructions: ["Turn the trail hip back without losing contact with the wall/chair.", "Shift and rotate so the lead hip replaces depth instead of moving toward the ball.", "Pause at impact-like position with pelvis open."],
    feel: "Both hips staying deep as the pelvis turns around you.",
    cues: ["Trail hip back", "Lead hip replaces", "Do not chase the ball"],
    commonMistakes: ["Hips moving toward the ball", "Locking knees", "Turning shoulders instead"],
    golfBenefit: "Direct rehearsal for maintaining pelvic depth and avoiding early extension.",
    regression: "Do it slower with hands on hips.",
    progression: "Add a slow club takeaway and downswing pump.",
    tags: ["pelvic-depth", "early-extension", "rotation", "golf-club"]
  }),
  drill({
    slug: "pallof-press-rotation-resist",
    name: "Pallof Press with Rotation Resist",
    category: "control",
    bodyFocus: ["obliques", "core", "hips"],
    swingFocus: ["anti-rotation", "posture", "sequencing"],
    equipment: ["bands", "open_floor"],
    defaultPrescription: "2-3 sets x 8 presses per side",
    defaultSets: 3,
    defaultRestSeconds: 45,
    setup: "Anchor a band at chest height. Stand side-on in athletic posture with hands at sternum.",
    instructions: ["Press the band straight out without letting your ribs or pelvis turn.", "Pause at full reach and breathe behind the brace.", "Return slowly without losing posture."],
    feel: "Obliques resisting rotation while hips and feet stay grounded.",
    cues: ["Zip ribs to pelvis", "Press straight", "Quiet belt buckle"],
    commonMistakes: ["Leaning away from the band", "Shrugging", "Letting knees cave"],
    golfBenefit: "Builds the bracing capacity to separate and rotate without leaking posture.",
    regression: "Use a lighter band or narrower press range.",
    progression: "Add a split stance or slow step-out.",
    tags: ["anti-rotation", "core", "posture", "bands"]
  }),
  drill({
    slug: "snap-down-to-stick",
    name: "Snap Down to Stick",
    category: "power",
    bodyFocus: ["feet", "ankles", "hips"],
    swingFocus: ["ground force", "braking", "athletic posture"],
    equipment: ["bodyweight", "open_floor"],
    defaultPrescription: "3 sets x 5 sticks",
    defaultSets: 3,
    defaultRestSeconds: 45,
    setup: "Stand tall on toes with arms overhead. Drop quickly into an athletic hinge and stick the landing quietly.",
    instructions: ["Rise tall, then snap the arms down as feet hit the floor.", "Land in golf-athletic posture with knees tracking toes.", "Hold the landing for two seconds."],
    feel: "Springy feet and a firm, quiet landing.",
    cues: ["Quiet feet", "Stick the floor", "Ribs down"],
    commonMistakes: ["Landing loud", "Knees collapsing", "Standing too upright"],
    golfBenefit: "Builds braking and ground-force awareness for faster rotational work.",
    regression: "Drop from flat feet instead of toes.",
    progression: "Add a small vertical hop before the stick.",
    tags: ["ground-force", "braking", "speed", "warmup"]
  }),
  drill({
    slug: "ankle-dorsiflexion-wall-drive",
    name: "Ankle Dorsiflexion Wall Drive",
    category: "mobility",
    bodyFocus: ["ankles", "calves", "feet"],
    swingFocus: ["posture", "pressure shift", "rotation support"],
    equipment: ["bodyweight", "open_floor"],
    defaultPrescription: "2 sets x 10 reps per side",
    defaultSets: 2,
    defaultRestSeconds: 20,
    setup: "Face a wall in a short lunge stance. Front foot points straight and heel stays down.",
    instructions: ["Drive the front knee toward the wall over the middle toes.", "Keep heel heavy and arch controlled.", "Pause at end range, then back out slowly."],
    feel: "Ankle and calf opening while the foot stays grounded.",
    cues: ["Heel down", "Knee over toes", "Control the arch"],
    commonMistakes: ["Heel lifting", "Foot spinning out", "Knee collapsing inside"],
    golfBenefit: "Restores ankle motion needed to stay in posture while rotating.",
    regression: "Move farther from the wall and use a smaller range.",
    progression: "Add a light dumbbell on the knee if available.",
    tags: ["ankle-dorsiflexion", "posture", "mobility", "daily"]
  })
];

export function getBaselineCoverage(results: BaselineResultInput[]) {
  const completedSlugs = new Set(
    results.filter((result) => result.status !== "not_tested").map((result) => result.testSlug)
  );
  const completed = baselineTests.filter((test) => completedSlugs.has(test.slug)).length;
  const total = baselineTests.length;

  return {
    completed,
    total,
    percent: total === 0 ? 0 : Math.round((completed / total) * 100)
  };
}
